title: Mery Paul
#logo: /asset/img/Photo
description: paul.mery@etu.umontpellier.fr
show_downloads: false
theme: jekyll-theme-minimal


layout: page
title: "TEST"
permalink: MeryPaul.github.io/pages/Etude_d'un_modèle_épidémiologique.md

