title: Mery Paul
logo: /asset/img/Photo
description: paul.mery@etu.umontpellier.fr
show_downloads: false
theme: jekyll-theme-minimal

#layout: page
#title: "Etude d'un modèle épidémiologique"
#permalink: MeryPaul.github.io/pages/Etude_d'un_modèle_épidémiologique.md

#layout: page
#title: "Etude de sensibilité"
#permalink: MeryPaul.github.io/pages/Etude_de_sensibilité.md

#layout: page
#title: "Nombre Irrationnel et fraction continue"
#permalink: MeryPaul.github.io/pages/Nombre_Irrationnel_et_fraction_continue.md

#layout: page
#title: "Problème de Stefan en 1D"
#permalink: MeryPaul.github.io/pages/Problème_de_Stefan.md

#layout: page
#title: "Introduction a la Théorie Géométrique des Groupes"
#permalink: MeryPaul.github.io/pages/théorie_géométrique_des_groupes.md
